spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: ENC(EVrQ4mK7IxMfZqoBPTWEzoHpBPZbqqhm)
    url: jdbc:mysql://${MYSQL_HOST:10.133.104.160}:3306/amsp
    username: app
    hikari:
      maximum-pool-size: 1
  jpa:
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect

management:
  endpoints:
    web:
      exposure:
        include: "*"
    info:
      enabled: true
server:
  servlet:
    context-path: /amsp/api/sams
  port: 8082
  
security:
       jwt:
         secret-key: ENC(gqdK8ngVBYFio4V4tQHdWcqMn52WkmIoipbpO3IShOBBRcFycqsuz51s08qI1IzwdR+wHWt6kdnw+15tTSlbqtA/6eWAVkB4vTVteutjFfk=)
services:
  endpoints:
    fetch-pbx-by-area-code: http://localhost:8080/amsp/api/masterdata/v1/pbxcluster/%s
    auth-token: http://linpubah160.gl.avaya.com:8082/amsp/api/auth/v1/login
    fetch-articles: http://localhost:8080/amsp/api/masterdata/v1/connections/%s/cluster/%s/articles
    open-sams-order:  http://localhost:8083/amsp/api/order/v1/sams-order
    fetch-sams-order: http://localhost:8083/amsp/api/order/v1/sams-order/%s
    delete-sams-order: http://localhost:8083/amsp/api/order/v1/sams-order
    change-sams-order: http://localhost:8083/amsp/api/order/v1/sams-order
    fetch-subscriber: http://localhost:8084/amsp/api/subscriber/v1/udmviews/subscriber/%s/%s
    fetch-connections-by-cluster-id: http://localhost:8080/amsp/api/masterdata/v1/clusters/%s/connections

  sams-account-username: shdhumal
  sams-account-pass: ENC(PiA5pIdvXgZCHpmywYOGJdX/9fNUbFul)

sams:
  api:
    key: ENC(q5ULcbTpVeHNqrehiq9yN6o5fIsDO7nL)
