spring:
  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    password: ENC(auhwDAnMDgn+gZzuRBE+HQINWo48HqSi)
    url: jdbc:oracle:thin:@lushraora02.gl.avaya.com:1526:salngdv7
    username: AMSP
    hikari:
      maximum-pool-size: 1
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql=true
logging:
  level:
    org:
      hibernate:
        type: trace
        orm:
          jdbc:
            bind: trace
    com:
      avaya: info

    
springdoc:
  show-actuator: true
  packages-to-scan:
  - com.avaya.amsp.masterdata.rest
management:
  endpoints:
    web:
      exposure:
        include: "*"
    info:
      enabled: true
    